# Generated by Django 3.0.7 on 2023-06-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230505_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.TextField(max_length=450),
        ),
    ]
