# Generated by Django 3.0.7 on 2023-06-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230614_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.TextField(max_length=250),
        ),
    ]
